version: '3.8'
services:
    app:
      build:
        dockerfile: Dockerfile
        context: .
        target: final
      ports:
        - 8080:8080
      restart: unless-stopped
      volumes:
        - .:/opt/app/api

    # postgres:
    #     image: postgres:16.0
    #     restart: always
    #     environment:
    #       - POSTGRES_USER=postgres
    #       - POSTGRES_PASSWORD=postgres
    #       - POSTGRES_DB=library-db
    #     logging:
    #       options:
    #         max-size: 10m
    #         max-file: "3"
    #     ports:
    #       - '5432:5432'
    #     volumes: 
    #       - ./postgres-data:/var/lib/postgresql/data
    #       # copy the sql script to create tables
    #       - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    