version: '3.8'
services:
    app:
      build:
        dockerfile: Dockerfile
        context: .
        target: final
      ports:
        - 8080:8080
      restart: unless-stopped
      depends_on:
        - postgresdb
      networks:
        - backend

    postgresdb:
        image: postgres:16.0
        container_name: pgcontainer
        restart: always
        environment:
          - POSTGRES_HOST=localhost
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=library-db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes: 
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./sql/insert_values.sql:/docker-entrypoint-initdb.d/insert_values.sql
        networks:
          - backend

networks:
  backend:
    driver: bridge