version: '3.8'
services:
    app:
      build:
        dockerfile: Dockerfile
        context: .
        target: final
      ports:
        - 8080:8080
      restart: unless-stopped

## TODO app running in container is not connecting to database, connection refused, need to solve that
    postgres:
        image: postgres:16.0
        container_name: pgcontainer
        restart: always
        environment:
          - POSTGRES_HOST=localhost
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=library-db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes: 
          - ./pgdata:/var/lib/postgresql
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./sql/insert_values.sql:/docker-entrypoint-initdb.d/insert_values.sql

# volumes:
#     pgdata: